### ISSUE TITLE
Takealug EPG Grabber kein support für Kodi 19 Matrix

### ISSUE THREAD

**Issue by henrijd** [DeBaschdi/repo#2]
Hi,

wenn man es versucht zu installieren sag es das xbmc.python 2.25 braucht.
Kodi 19 Matrix nutzt aber schon Python 3.

Kann man einfach einen update machen wo es dann Python 3 benutzt kann oder muss man alles auf python 3 umschreiben?

Bis jetzt finde ich leider keinen anderen EPG Grabber der Kodi 19 Unterstützt. Und eine altere version kann ich nicht einfach nutzen da ich das neue Simple IPTV Client brauche für Timeshift und Aufnahmen, etc.

Mit Tvheadend have ich es auch versucht aber irgendwie klappt es nicht.

Wäre es viel aufwändig? Ansonsten würde ich mir mal schlau machen wie einen Kodi Add-On auf Kodi 19 aufrüstet von Programmierung habe ich leider Keine ahnung :(

Beste Grüße
HenriJD

**Comment by DeBaschdi** [comment]
Hi, im kodinerds Repo findest du auch eine Matrix Version, mein privates Repo wird erst beim stable Matrix Release umgestellt. 
L.G
